name: Build and push Docker image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Release tag
        id: releasetag
        run: |
          now=`date "+%Y.%m"`
          echo "date=$now" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: martabal
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            martabal/alpine:latest
            martabal/alpine:${{ steps.releasetag.outputs.date }}
            ghcr.io/${{ github.repository_owner }}/alpine:${{ steps.releasetag.outputs.date }}
            ghcr.io/${{ github.repository_owner }}/alpine:latest

